### ISSUE TITLE
Owner can call `suicide` at any time to claim all bets for himself.

### ISSUE THREAD

**Issue by beether** [ethorse/ethorse-core#18]
Hi. I actually read the contract. This seems like a pretty big issue to me.

**Comment by louiedp3** [comment]
Doesn't the modifier `onlyOwner` prevent this? The `msg.sender` has to be the person who created the contract.

**Comment by ethorse** [comment]
@beether Thanks for your interest and time in looking into ethorse. Though the behavior of the function is true as posted, it is used only for development purpose. The version of contract which gets deployed won't have the method.
The source of the contract can be verified here https://ropsten.etherscan.io/address/0x204D3988F0BcCca29716aF64ac555a5fC1dc7031#code

**Comment by ethorse** [comment]
@louiedp3 Good catch. The method can be called only by the owner of the contract. The smart contracts need to as trustless as possible and even the owner shouldn't have that kind of power of the races. As mentioned, this function is used only for development purpose.

**Comment by ethorse** [comment]
Feel free to try the [dApp](https://ethorse.github.io/Betting/) and post any other issue or feedback you have.

I will anyway move those functions to another branch and keep the master production ready. Till then I will keep this issue open. Thank you for your contribution.
