### ISSUE TITLE
Draw between BTC and ETH will dismiss LTC result

### ISSUE THREAD

**Issue by fravoll** [ethorse/ethorse-core#19]
In betting.sol in the reward() function in case of a draw between BTC and ETH, the delta of LTC will not be checked as fas as I understand.
So a result of 
- BTC_delta = 10000
- ETH_delta = 10000
- LTC_delta = 15000

would mark BTC and ETH as winners without considering LTC.

**Comment by ethorse** [comment]
Great catch. We will update it before the mainnet launch. I will keep this issue open till then.

**Comment by ethorse** [comment]
This has been fixed in #23. If there is any other changes to be, we can reopen the issue
