### ISSUE TITLE
Problem with constant functions

### ISSUE THREAD

**Issue by NickErrant** [ethorse/ethorse-core#7]
Reposting my reddit comment here, as no one seems to have fully grasped the issue yet:

Declaring a function constant, doesn't prevent it from modifying state. Ethereum docs explicitly say it's not enforced by the complier yet: http://solidity.readthedocs.io/en/develop/contracts.html#view-functions

Calling calculate_reward() or check_reward() based on the contract's ABI, would only run locally (thanks to the constant declaration), and that's why you wouldn't see the state change propagated to the network. However it's trivial to invoke a function without regard to it's ABI, and the contract's state absolutely would change. Multiple invocations of calculate_reward() in this manner would increase the reward beyond the intended amount, stealing funds.

Right now what's happening is your calls to check_reward() are only running locally. The calculate_reward() call in claim_reward() is effectively ignoring the constant declaration, since there are no mechanisma to run the function outside the EVM (as you do when you use call locally) or to actually prevent state changes.

All this together makes it seem like constant is preventing the state change, but it is not. When you're testing, you call check_reward() locally so the calculate_reward() call in there doesn't change state, no matter how many times you call it. claim_reward() can only be called once per sender, so while the calculate_reward() call in there does change state, the contract will behave as expected. Your test cases are giving you a false sense of security. Again, it is trivial to invoke calculate_reward() non-locally, bypassing your intended security mechanism.

calculate_reward() should be refactored to use function scoped variables, not state variables, so that it's actually "constant"; and made to return the calculated amount, not store it in rewardIndex. rewardIndex should be removed, and the rewarded flag should be moved to user_info.

**Comment by ethorse** [comment]
#10
