### ISSUE TITLE
update allows malicious contract owner to cheat

### ISSUE THREAD

**Issue by NickErrant** [ethorse/ethorse-core#8]
Since update() can be called multiple times, a malicious contract owner could end the race at any time.

This can be used by said owner to cheat the race by placing a large bet on the currently winning horse, then immediately starting and ending the race by calling update() with a high enough delay to make `delay += 60` overflow to 0 and locking_duration == 0.

**Comment by ethorse** [comment]
#10

**Comment by ethorse** [comment]
#10
